// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqhlzi8IPAH_KndOBzIw69gPeVBUIzNi4',
    appId: '1:411658702585:web:3dfafec527ff26bef31c28',
    messagingSenderId: '411658702585',
    projectId: 'tscoffee-8eaab',
    authDomain: 'tscoffee-8eaab.firebaseapp.com',
    storageBucket: 'tscoffee-8eaab.firebasestorage.app',
    measurementId: 'G-35DBCSCF0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Kt2yWzRv_h5JHwd-kQGvyRyhLTFhYDE',
    appId: '1:411658702585:android:83fa004d101047c3f31c28',
    messagingSenderId: '411658702585',
    projectId: 'tscoffee-8eaab',
    storageBucket: 'tscoffee-8eaab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM9OJqSXm3s2SxCQ53S6DlpUGIHJQHYaU',
    appId: '1:411658702585:ios:22d00d6a243cc7e4f31c28',
    messagingSenderId: '411658702585',
    projectId: 'tscoffee-8eaab',
    storageBucket: 'tscoffee-8eaab.firebasestorage.app',
    iosBundleId: 'com.example.thoiTiet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM9OJqSXm3s2SxCQ53S6DlpUGIHJQHYaU',
    appId: '1:411658702585:ios:22d00d6a243cc7e4f31c28',
    messagingSenderId: '411658702585',
    projectId: 'tscoffee-8eaab',
    storageBucket: 'tscoffee-8eaab.firebasestorage.app',
    iosBundleId: 'com.example.thoiTiet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqhlzi8IPAH_KndOBzIw69gPeVBUIzNi4',
    appId: '1:411658702585:web:983aa601cc25f2caf31c28',
    messagingSenderId: '411658702585',
    projectId: 'tscoffee-8eaab',
    authDomain: 'tscoffee-8eaab.firebaseapp.com',
    storageBucket: 'tscoffee-8eaab.firebasestorage.app',
    measurementId: 'G-32JLKHYY5S',
  );
}
